[project]
name = "alphabetagamma"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.3.5",
    "dotenv>=0.9.9",
    "openai>=2.8.1",
    "python-dotenv>=1.2.1",
    "tqdm>=4.67.1",
]

[tool.uv]
